name: Validate JSONs

on: [pull_request]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Validate JSON
        uses: OrRosenblatt/validate-json-action@0.1.0
        env:
          INPUT_JSONS: ./data/users.json
