name: Validate JSONs

on: [pull_request]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: OrRosenblatt/validate-json-action@0.1.0
        with:
          # One or more relative file paths under the repository (seperated by comma) of the JSON files to validate with the schema provided.
          json: ./data/users.json
