name: Validate JSON

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Validate JSON
      uses: OrRosenblatt/validate-json-action@0.1.0

